name: Custom Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      input1:
        description: 'Take sample input'
        required: true

jobs:
  check_input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print Input
        run: |
          echo "Confirming your input was ${{ github.event.inputs.input1 }}"
