name: Custom Workflow
on:
  workflow_dispatch:

jobs:

  core-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node dependencies
        run: npm ci

      - name: Install python dependenceis
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run Python function
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          TOKEN: ${{ secrets.TOKEN }}
        run: python srh_jamaica.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output
          git add flows
          git commit -m "Add output files"
          git push
