name: Produce RapidPro flows
on:
  workflow_dispatch:
    inputs:
      rp_import:
        description: Import flows into RapidPro
        type: boolean
        required: false
        default: false

jobs:

  core-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node dependencies
        run: npm ci

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          RP_HOST: ${{ vars.RP_HOST }}
          RP_IMPORT: ${{ inputs.rp_import }}
          RP_PASS: ${{ secrets.RP_PASS }}
          RP_USER: ${{ secrets.RP_USER }}
        run: python srh_jamaica.py

      - name: Publish output folder
        uses: actions/upload-artifact@v3
        with:
          name: Output Files
          path: output
