name: Custom Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  core-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node dependencies
        run: npm ci

      - name: Install python dependenceis
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run Python function
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          TOKEN: ${{ secrets.TOKEN }}
        run: python srh_jamaica.py "CREDENTIALS" "TOKEN"
